# CMake generated Testfile for 
# Source directory: /home/nakada/GitHub/ShogiBoardQ/tests
# Build directory: /home/nakada/GitHub/ShogiBoardQ/build-review/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tst_coredatastructures "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_coredatastructures")
set_tests_properties(tst_coredatastructures PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;71;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_shogiboard "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_shogiboard")
set_tests_properties(tst_shogiboard PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;86;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_sfentracer "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_sfentracer")
set_tests_properties(tst_sfentracer PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;97;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_shogiclock "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_shogiclock")
set_tests_properties(tst_shogiclock PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;106;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_kifconverter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_kifconverter")
set_tests_properties(tst_kifconverter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;115;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_ki2converter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_ki2converter")
set_tests_properties(tst_ki2converter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;130;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_csaconverter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_csaconverter")
set_tests_properties(tst_csaconverter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;146;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_jkfconverter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_jkfconverter")
set_tests_properties(tst_jkfconverter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;158;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_usiconverter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_usiconverter")
set_tests_properties(tst_usiconverter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;170;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_usenconverter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_usenconverter")
set_tests_properties(tst_usenconverter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;182;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_kifubranchtree "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_kifubranchtree")
set_tests_properties(tst_kifubranchtree PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;197;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_livegamesession "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_livegamesession")
set_tests_properties(tst_livegamesession PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;204;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_navigation "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_navigation")
set_tests_properties(tst_navigation PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;213;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_gamerecordmodel "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_gamerecordmodel")
set_tests_properties(tst_gamerecordmodel PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;228;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_kifu_comment_sync "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_kifu_comment_sync")
set_tests_properties(tst_kifu_comment_sync PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;250;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_josekiwindow "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_josekiwindow")
set_tests_properties(tst_josekiwindow PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;272;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_positionedit_gamestart "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_positionedit_gamestart")
set_tests_properties(tst_positionedit_gamestart PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;291;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_preset_gamestart_cleanup "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_preset_gamestart_cleanup")
set_tests_properties(tst_preset_gamestart_cleanup PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;304;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_integration "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_integration")
set_tests_properties(tst_integration PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;324;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_usiprotocolhandler "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_usiprotocolhandler")
set_tests_properties(tst_usiprotocolhandler PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;346;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_ui_display_consistency "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_ui_display_consistency")
set_tests_properties(tst_ui_display_consistency PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;356;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_analysisflow "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_analysisflow")
set_tests_properties(tst_analysisflow PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;389;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_game_start_flow "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_game_start_flow")
set_tests_properties(tst_game_start_flow PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;404;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_fmvbitboard81 "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_fmvbitboard81")
set_tests_properties(tst_fmvbitboard81 PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;421;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_fmvconverter "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_fmvconverter")
set_tests_properties(tst_fmvconverter PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;427;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_fmvposition "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_fmvposition")
set_tests_properties(tst_fmvposition PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;442;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_fmvlegalcore "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_fmvlegalcore")
set_tests_properties(tst_fmvlegalcore PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;457;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_enginemovevalidator_compat "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_enginemovevalidator_compat")
set_tests_properties(tst_enginemovevalidator_compat PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;467;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_enginemovevalidator_context "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_enginemovevalidator_context")
set_tests_properties(tst_enginemovevalidator_context PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;477;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_fmv_perft "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_fmv_perft")
set_tests_properties(tst_fmv_perft PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;487;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
add_test(tst_enginemovevalidator_crosscheck "/home/nakada/GitHub/ShogiBoardQ/build-review/tests/tst_enginemovevalidator_crosscheck")
set_tests_properties(tst_enginemovevalidator_crosscheck PROPERTIES  _BACKTRACE_TRIPLES "/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;65;add_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;497;add_shogi_test;/home/nakada/GitHub/ShogiBoardQ/tests/CMakeLists.txt;0;")
