// This file is autogenerated. Changes will be overwritten.
#include "AAGGKE4ILT/moc_errorbus.cpp"
#include "MV7IEL3DTJ/moc_shogiboard.cpp"
#include "BH3NS63JAO/moc_shogigamecontroller.cpp"
#include "BH3NS63JAO/moc_turnmanager.cpp"
