// This file is autogenerated. Changes will be overwritten.
#include "AAGGKE4ILT/moc_errorbus.cpp"
#include "MV7IEL3DTJ/moc_shogiboard.cpp"
#include "BH3NS63JAO/moc_shogigamecontroller.cpp"
#include "BH3NS63JAO/moc_turnmanager.cpp"
#include "5ISS6V5EH3/moc_kifubranchtree.cpp"
#include "5ISS6V5EH3/moc_kifunavigationstate.cpp"
#include "5ISS6V5EH3/moc_livegamesession.cpp"
#include "D2HGCNADXF/moc_kifunavigationcontroller.cpp"
