#pragma once

/// @file logcategories.h
/// @brief アプリケーション全体で使用するログカテゴリの宣言

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcApp)
Q_DECLARE_LOGGING_CATEGORY(lcCore)
Q_DECLARE_LOGGING_CATEGORY(lcGame)
Q_DECLARE_LOGGING_CATEGORY(lcKifu)
Q_DECLARE_LOGGING_CATEGORY(lcEngine)
Q_DECLARE_LOGGING_CATEGORY(lcUi)
Q_DECLARE_LOGGING_CATEGORY(lcUiPolicy)
Q_DECLARE_LOGGING_CATEGORY(lcNetwork)
Q_DECLARE_LOGGING_CATEGORY(lcView)
Q_DECLARE_LOGGING_CATEGORY(lcBoard)
Q_DECLARE_LOGGING_CATEGORY(lcAnalysis)
Q_DECLARE_LOGGING_CATEGORY(lcShogiClock)
Q_DECLARE_LOGGING_CATEGORY(lcNavigation)
