/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.10.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionSave;
    QAction *actionSaveAs;
    QAction *actionSaveBoardImage;
    QAction *actionPasteKifu;
    QAction *actionCopyBoardToClipboard;
    QAction *actionCopyEvalGraphToClipboard;
    QAction *actionFlipBoard;
    QAction *actionStartGame;
    QAction *actionResign;
    QAction *actionBreakOffGame;
    QAction *actionQuit;
    QAction *actionAnalyzeKifu;
    QAction *actionStartEditPosition;
    QAction *actionSetHiratePosition;
    QAction *actionSetTsumePosition;
    QAction *actionReturnAllPiecesToStand;
    QAction *actionChangeTurn;
    QAction *actionEngineSettings;
    QAction *actionOpenWebsite;
    QAction *actionUsage;
    QAction *actionVersionInfo;
    QAction *actionAboutQt;
    QAction *actionCopyKIF;
    QAction *actionCopyKI2;
    QAction *actionCopyCSA;
    QAction *actionCopyUSICurrent;
    QAction *actionCopySFEN;
    QAction *actionCopyBOD;
    QAction *actionNewGame;
    QAction *actionOpenKifuFile;
    QAction *actionUndoMove;
    QAction *actionMakeImmediateMove;
    QAction *actionEnlargeBoard;
    QAction *actionShrinkBoard;
    QAction *actionEndEditPosition;
    QAction *actionTsumeShogiSearch;
    QAction *actionStopTsumeSearch;
    QAction *actionJishogiScore;
    QAction *actionNyugyokuDeclaration;
    QAction *actionCopyUSIAll;
    QAction *actionCopyJKF;
    QAction *actionCopyUSEN;
    QAction *actionCSA;
    QAction *actionCancelAnalyzeKifu;
    QAction *actionMenuWindow;
    QAction *actionLanguageSystem;
    QAction *actionLanguageJapanese;
    QAction *actionLanguageEnglish;
    QAction *actionToolBar;
    QAction *actionSfenCollectionViewer;
    QAction *actionResetDockLayout;
    QAction *actionSaveDockLayout;
    QAction *actionLockDocks;
    QAction *actionSavedLayoutsPlaceholder;
    QAction *actionSaveEvaluationGraph;
    QAction *actionTsumeshogiGenerator;
    QWidget *centralwidget;
    QMenuBar *menubar;
    QMenu *File;
    QMenu *Edit;
    QMenu *copyGameRecord;
    QMenu *shogiPositionCopy;
    QMenu *Display;
    QMenu *menuSavedLayouts;
    QMenu *Game;
    QMenu *Setting;
    QMenu *menuLanguage;
    QMenu *Help;
    QStatusBar *statusbar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(892, 600);
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName("actionSave");
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/actions/actionSave.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSave->setIcon(icon);
        actionSaveAs = new QAction(MainWindow);
        actionSaveAs->setObjectName("actionSaveAs");
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/images/actions/actionSaveAs.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSaveAs->setIcon(icon1);
        actionSaveBoardImage = new QAction(MainWindow);
        actionSaveBoardImage->setObjectName("actionSaveBoardImage");
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/images/actions/actionSaveBoardImage.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSaveBoardImage->setIcon(icon2);
        actionPasteKifu = new QAction(MainWindow);
        actionPasteKifu->setObjectName("actionPasteKifu");
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/images/actions/actionPasteKifu.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionPasteKifu->setIcon(icon3);
        actionCopyBoardToClipboard = new QAction(MainWindow);
        actionCopyBoardToClipboard->setObjectName("actionCopyBoardToClipboard");
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/images/actions/actionCopyBoardToClipboard.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyBoardToClipboard->setIcon(icon4);
        actionCopyEvalGraphToClipboard = new QAction(MainWindow);
        actionCopyEvalGraphToClipboard->setObjectName("actionCopyEvalGraphToClipboard");
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/images/actions/actionCopyEvalGraphToClipboard.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyEvalGraphToClipboard->setIcon(icon5);
        actionFlipBoard = new QAction(MainWindow);
        actionFlipBoard->setObjectName("actionFlipBoard");
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/images/actions/actionFlipBoard.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionFlipBoard->setIcon(icon6);
        actionStartGame = new QAction(MainWindow);
        actionStartGame->setObjectName("actionStartGame");
        actionStartGame->setEnabled(true);
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/images/actions/actionStartGame.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionStartGame->setIcon(icon7);
        actionResign = new QAction(MainWindow);
        actionResign->setObjectName("actionResign");
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/images/actions/actionResign.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionResign->setIcon(icon8);
        actionBreakOffGame = new QAction(MainWindow);
        actionBreakOffGame->setObjectName("actionBreakOffGame");
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/images/actions/actionBreakOffGame.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionBreakOffGame->setIcon(icon9);
        actionBreakOffGame->setVisible(true);
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName("actionQuit");
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/images/actions/actionQuit.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionQuit->setIcon(icon10);
        actionAnalyzeKifu = new QAction(MainWindow);
        actionAnalyzeKifu->setObjectName("actionAnalyzeKifu");
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/images/actions/actionAnalyzeKifu.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionAnalyzeKifu->setIcon(icon11);
        actionStartEditPosition = new QAction(MainWindow);
        actionStartEditPosition->setObjectName("actionStartEditPosition");
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/images/actions/actionStartEditPosition.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionStartEditPosition->setIcon(icon12);
        actionSetHiratePosition = new QAction(MainWindow);
        actionSetHiratePosition->setObjectName("actionSetHiratePosition");
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/images/actions/actionSetHiratePosition.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSetHiratePosition->setIcon(icon13);
        actionSetTsumePosition = new QAction(MainWindow);
        actionSetTsumePosition->setObjectName("actionSetTsumePosition");
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/images/actions/actionSetTsumePosition.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSetTsumePosition->setIcon(icon14);
        actionReturnAllPiecesToStand = new QAction(MainWindow);
        actionReturnAllPiecesToStand->setObjectName("actionReturnAllPiecesToStand");
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/images/actions/actionReturnAllPiecesToStand.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionReturnAllPiecesToStand->setIcon(icon15);
        actionChangeTurn = new QAction(MainWindow);
        actionChangeTurn->setObjectName("actionChangeTurn");
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/images/actions/actionChangeTurn.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionChangeTurn->setIcon(icon16);
        actionEngineSettings = new QAction(MainWindow);
        actionEngineSettings->setObjectName("actionEngineSettings");
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/images/actions/actionEngineSettings.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionEngineSettings->setIcon(icon17);
        actionOpenWebsite = new QAction(MainWindow);
        actionOpenWebsite->setObjectName("actionOpenWebsite");
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/images/actions/actionOpenWebsite.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionOpenWebsite->setIcon(icon18);
        actionUsage = new QAction(MainWindow);
        actionUsage->setObjectName("actionUsage");
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/images/actions/actionUsage.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionUsage->setIcon(icon19);
        actionVersionInfo = new QAction(MainWindow);
        actionVersionInfo->setObjectName("actionVersionInfo");
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/images/actions/actionVersionInfo.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionVersionInfo->setIcon(icon20);
        actionAboutQt = new QAction(MainWindow);
        actionAboutQt->setObjectName("actionAboutQt");
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/images/actions/actionAboutQt.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionAboutQt->setIcon(icon21);
        actionCopyKIF = new QAction(MainWindow);
        actionCopyKIF->setObjectName("actionCopyKIF");
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/images/actions/actionCopyKIF.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyKIF->setIcon(icon22);
        actionCopyKI2 = new QAction(MainWindow);
        actionCopyKI2->setObjectName("actionCopyKI2");
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/images/actions/actionCopyKI2.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyKI2->setIcon(icon23);
        actionCopyCSA = new QAction(MainWindow);
        actionCopyCSA->setObjectName("actionCopyCSA");
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/images/actions/actionCopyCSA.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyCSA->setIcon(icon24);
        actionCopyUSICurrent = new QAction(MainWindow);
        actionCopyUSICurrent->setObjectName("actionCopyUSICurrent");
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/images/actions/actionCopyUSICurrent.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyUSICurrent->setIcon(icon25);
        actionCopySFEN = new QAction(MainWindow);
        actionCopySFEN->setObjectName("actionCopySFEN");
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/images/actions/actionCopySFEN.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopySFEN->setIcon(icon26);
        actionCopyBOD = new QAction(MainWindow);
        actionCopyBOD->setObjectName("actionCopyBOD");
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/images/actions/actionCopyBOD.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyBOD->setIcon(icon27);
        actionNewGame = new QAction(MainWindow);
        actionNewGame->setObjectName("actionNewGame");
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/images/actions/actionNewGame.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionNewGame->setIcon(icon28);
        actionOpenKifuFile = new QAction(MainWindow);
        actionOpenKifuFile->setObjectName("actionOpenKifuFile");
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/images/actions/actionOpenKifuFile.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionOpenKifuFile->setIcon(icon29);
        actionUndoMove = new QAction(MainWindow);
        actionUndoMove->setObjectName("actionUndoMove");
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/images/actions/actionUndoMove.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionUndoMove->setIcon(icon30);
        actionMakeImmediateMove = new QAction(MainWindow);
        actionMakeImmediateMove->setObjectName("actionMakeImmediateMove");
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/images/actions/actionMakeImmediateMove.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionMakeImmediateMove->setIcon(icon31);
        actionEnlargeBoard = new QAction(MainWindow);
        actionEnlargeBoard->setObjectName("actionEnlargeBoard");
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/images/actions/actionEnlargeBoard.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionEnlargeBoard->setIcon(icon32);
        actionShrinkBoard = new QAction(MainWindow);
        actionShrinkBoard->setObjectName("actionShrinkBoard");
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/images/actions/actionShrinkBoard.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionShrinkBoard->setIcon(icon33);
        actionEndEditPosition = new QAction(MainWindow);
        actionEndEditPosition->setObjectName("actionEndEditPosition");
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/images/actions/actionEndEditPosition.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionEndEditPosition->setIcon(icon34);
        actionTsumeShogiSearch = new QAction(MainWindow);
        actionTsumeShogiSearch->setObjectName("actionTsumeShogiSearch");
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/images/actions/actionTsumeShogiSearch.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionTsumeShogiSearch->setIcon(icon35);
        actionStopTsumeSearch = new QAction(MainWindow);
        actionStopTsumeSearch->setObjectName("actionStopTsumeSearch");
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/images/actions/actionCancelTsumeShogiSearch.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionStopTsumeSearch->setIcon(icon36);
        actionJishogiScore = new QAction(MainWindow);
        actionJishogiScore->setObjectName("actionJishogiScore");
        QIcon icon37;
        icon37.addFile(QString::fromUtf8(":/images/actions/actionJishogiScore.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionJishogiScore->setIcon(icon37);
        actionNyugyokuDeclaration = new QAction(MainWindow);
        actionNyugyokuDeclaration->setObjectName("actionNyugyokuDeclaration");
        QIcon icon38;
        icon38.addFile(QString::fromUtf8(":/images/actions/actionNyugyokuDeclaration.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionNyugyokuDeclaration->setIcon(icon38);
        actionCopyUSIAll = new QAction(MainWindow);
        actionCopyUSIAll->setObjectName("actionCopyUSIAll");
        QIcon icon39;
        icon39.addFile(QString::fromUtf8(":/images/actions/actionCopyUSIAll.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyUSIAll->setIcon(icon39);
        actionCopyJKF = new QAction(MainWindow);
        actionCopyJKF->setObjectName("actionCopyJKF");
        QIcon icon40;
        icon40.addFile(QString::fromUtf8(":/images/actions/actionCopyJKF.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCopyJKF->setIcon(icon40);
        actionCopyUSEN = new QAction(MainWindow);
        actionCopyUSEN->setObjectName("actionCopyUSEN");
        actionCopyUSEN->setIcon(icon39);
        actionCSA = new QAction(MainWindow);
        actionCSA->setObjectName("actionCSA");
        QIcon icon41;
        icon41.addFile(QString::fromUtf8(":/images/actions/actionCSA.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCSA->setIcon(icon41);
        actionCancelAnalyzeKifu = new QAction(MainWindow);
        actionCancelAnalyzeKifu->setObjectName("actionCancelAnalyzeKifu");
        QIcon icon42;
        icon42.addFile(QString::fromUtf8(":/images/actions/actionCancelAnalyzeKifu.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionCancelAnalyzeKifu->setIcon(icon42);
        actionMenuWindow = new QAction(MainWindow);
        actionMenuWindow->setObjectName("actionMenuWindow");
        QIcon icon43;
        icon43.addFile(QString::fromUtf8(":/images/actions/actionMenuWindow.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionMenuWindow->setIcon(icon43);
        actionLanguageSystem = new QAction(MainWindow);
        actionLanguageSystem->setObjectName("actionLanguageSystem");
        actionLanguageSystem->setCheckable(true);
        QIcon icon44;
        icon44.addFile(QString::fromUtf8(":/images/actions/actionLanguageSystem.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionLanguageSystem->setIcon(icon44);
        actionLanguageJapanese = new QAction(MainWindow);
        actionLanguageJapanese->setObjectName("actionLanguageJapanese");
        actionLanguageJapanese->setCheckable(true);
        QIcon icon45;
        icon45.addFile(QString::fromUtf8(":/images/actions/actionLanguageJapanese.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionLanguageJapanese->setIcon(icon45);
        actionLanguageEnglish = new QAction(MainWindow);
        actionLanguageEnglish->setObjectName("actionLanguageEnglish");
        actionLanguageEnglish->setCheckable(true);
        QIcon icon46;
        icon46.addFile(QString::fromUtf8(":/images/actions/actionLanguageEnglish.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionLanguageEnglish->setIcon(icon46);
        actionToolBar = new QAction(MainWindow);
        actionToolBar->setObjectName("actionToolBar");
        actionToolBar->setCheckable(true);
        actionToolBar->setChecked(true);
        QIcon icon47;
        icon47.addFile(QString::fromUtf8(":/images/actions/actionToolbar.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionToolBar->setIcon(icon47);
        actionSfenCollectionViewer = new QAction(MainWindow);
        actionSfenCollectionViewer->setObjectName("actionSfenCollectionViewer");
        QIcon icon48;
        icon48.addFile(QString::fromUtf8(":/images/actions/actionPositionViewer.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSfenCollectionViewer->setIcon(icon48);
        actionResetDockLayout = new QAction(MainWindow);
        actionResetDockLayout->setObjectName("actionResetDockLayout");
        QIcon icon49;
        icon49.addFile(QString::fromUtf8(":/images/actions/actionResetDockLayout.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionResetDockLayout->setIcon(icon49);
        actionSaveDockLayout = new QAction(MainWindow);
        actionSaveDockLayout->setObjectName("actionSaveDockLayout");
        QIcon icon50;
        icon50.addFile(QString::fromUtf8(":/images/actions/actionSaveDockLayout.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSaveDockLayout->setIcon(icon50);
        actionLockDocks = new QAction(MainWindow);
        actionLockDocks->setObjectName("actionLockDocks");
        actionLockDocks->setCheckable(true);
        actionSavedLayoutsPlaceholder = new QAction(MainWindow);
        actionSavedLayoutsPlaceholder->setObjectName("actionSavedLayoutsPlaceholder");
        actionSavedLayoutsPlaceholder->setEnabled(false);
        actionSaveEvaluationGraph = new QAction(MainWindow);
        actionSaveEvaluationGraph->setObjectName("actionSaveEvaluationGraph");
        QIcon icon51;
        icon51.addFile(QString::fromUtf8(":/images/actions/actionSaveEvalGraphImage.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionSaveEvaluationGraph->setIcon(icon51);
        actionTsumeshogiGenerator = new QAction(MainWindow);
        actionTsumeshogiGenerator->setObjectName("actionTsumeshogiGenerator");
        QIcon icon52;
        icon52.addFile(QString::fromUtf8(":/images/actions/actionTsumeshogiGenerator.svg"), QSize(), QIcon::Mode::Normal, QIcon::State::Off);
        actionTsumeshogiGenerator->setIcon(icon52);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 892, 31));
        File = new QMenu(menubar);
        File->setObjectName("File");
        Edit = new QMenu(menubar);
        Edit->setObjectName("Edit");
        copyGameRecord = new QMenu(Edit);
        copyGameRecord->setObjectName("copyGameRecord");
        shogiPositionCopy = new QMenu(Edit);
        shogiPositionCopy->setObjectName("shogiPositionCopy");
        Display = new QMenu(menubar);
        Display->setObjectName("Display");
        menuSavedLayouts = new QMenu(Display);
        menuSavedLayouts->setObjectName("menuSavedLayouts");
        Game = new QMenu(menubar);
        Game->setObjectName("Game");
        Setting = new QMenu(menubar);
        Setting->setObjectName("Setting");
        menuLanguage = new QMenu(Setting);
        menuLanguage->setObjectName("menuLanguage");
        Help = new QMenu(menubar);
        Help->setObjectName("Help");
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName("toolBar");
        MainWindow->addToolBar(Qt::ToolBarArea::TopToolBarArea, toolBar);

        menubar->addAction(File->menuAction());
        menubar->addAction(Edit->menuAction());
        menubar->addAction(Display->menuAction());
        menubar->addAction(Game->menuAction());
        menubar->addAction(Setting->menuAction());
        menubar->addAction(Help->menuAction());
        File->addAction(actionNewGame);
        File->addAction(actionOpenKifuFile);
        File->addAction(actionSave);
        File->addAction(actionSaveAs);
        File->addSeparator();
        File->addAction(actionSaveBoardImage);
        File->addAction(actionSaveEvaluationGraph);
        File->addSeparator();
        File->addAction(actionQuit);
        Edit->addAction(copyGameRecord->menuAction());
        Edit->addAction(shogiPositionCopy->menuAction());
        Edit->addAction(actionPasteKifu);
        Edit->addSeparator();
        Edit->addAction(actionSfenCollectionViewer);
        Edit->addSeparator();
        Edit->addAction(actionCopyBoardToClipboard);
        Edit->addAction(actionCopyEvalGraphToClipboard);
        Edit->addSeparator();
        Edit->addAction(actionStartEditPosition);
        Edit->addAction(actionEndEditPosition);
        Edit->addAction(actionSetHiratePosition);
        Edit->addAction(actionSetTsumePosition);
        Edit->addAction(actionReturnAllPiecesToStand);
        Edit->addAction(actionChangeTurn);
        copyGameRecord->addAction(actionCopyKIF);
        copyGameRecord->addAction(actionCopyKI2);
        copyGameRecord->addAction(actionCopyCSA);
        copyGameRecord->addAction(actionCopyUSICurrent);
        copyGameRecord->addAction(actionCopyUSIAll);
        copyGameRecord->addAction(actionCopyJKF);
        copyGameRecord->addAction(actionCopyUSEN);
        shogiPositionCopy->addAction(actionCopySFEN);
        shogiPositionCopy->addAction(actionCopyBOD);
        Display->addAction(actionFlipBoard);
        Display->addAction(actionEnlargeBoard);
        Display->addAction(actionShrinkBoard);
        Display->addSeparator();
        Display->addAction(actionToolBar);
        Display->addSeparator();
        Display->addAction(actionResetDockLayout);
        Display->addAction(actionSaveDockLayout);
        Display->addAction(menuSavedLayouts->menuAction());
        Display->addAction(actionLockDocks);
        Display->addSeparator();
        menuSavedLayouts->addAction(actionSavedLayoutsPlaceholder);
        Game->addAction(actionStartGame);
        Game->addAction(actionCSA);
        Game->addSeparator();
        Game->addAction(actionResign);
        Game->addAction(actionUndoMove);
        Game->addAction(actionMakeImmediateMove);
        Game->addAction(actionBreakOffGame);
        Game->addSeparator();
        Game->addAction(actionAnalyzeKifu);
        Game->addAction(actionCancelAnalyzeKifu);
        Game->addSeparator();
        Game->addAction(actionTsumeShogiSearch);
        Game->addAction(actionStopTsumeSearch);
        Game->addAction(actionTsumeshogiGenerator);
        Game->addSeparator();
        Game->addAction(actionJishogiScore);
        Game->addAction(actionNyugyokuDeclaration);
        Setting->addAction(actionEngineSettings);
        Setting->addAction(menuLanguage->menuAction());
        menuLanguage->addAction(actionLanguageSystem);
        menuLanguage->addAction(actionLanguageJapanese);
        menuLanguage->addAction(actionLanguageEnglish);
        Help->addAction(actionOpenWebsite);
        Help->addAction(actionUsage);
        Help->addSeparator();
        Help->addAction(actionVersionInfo);
        Help->addAction(actionAboutQt);
        toolBar->addAction(actionOpenKifuFile);
        toolBar->addAction(actionSave);
        toolBar->addAction(actionStartGame);
        toolBar->addAction(actionResign);
        toolBar->addAction(actionUndoMove);
        toolBar->addAction(actionMakeImmediateMove);
        toolBar->addAction(actionBreakOffGame);
        toolBar->addAction(actionAnalyzeKifu);
        toolBar->addAction(actionTsumeShogiSearch);
        toolBar->addAction(actionFlipBoard);
        toolBar->addAction(actionEnlargeBoard);
        toolBar->addAction(actionShrinkBoard);
        toolBar->addAction(actionCSA);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "\345\260\206\346\243\213\347\233\244Q", nullptr));
        actionSave->setText(QCoreApplication::translate("MainWindow", "\344\270\212\346\233\270\343\201\215\344\277\235\345\255\230", nullptr));
#if QT_CONFIG(shortcut)
        actionSave->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+S", nullptr));
#endif // QT_CONFIG(shortcut)
        actionSaveAs->setText(QCoreApplication::translate("MainWindow", "\345\220\215\345\211\215\343\202\222\344\273\230\343\201\221\343\201\246\344\277\235\345\255\230", nullptr));
#if QT_CONFIG(shortcut)
        actionSaveAs->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+A", nullptr));
#endif // QT_CONFIG(shortcut)
        actionSaveBoardImage->setText(QCoreApplication::translate("MainWindow", "\345\260\206\346\243\213\347\233\244\343\201\256\347\224\273\345\203\217\343\202\222\343\203\225\343\202\241\343\202\244\343\203\253\343\201\253\344\277\235\345\255\230", nullptr));
        actionPasteKifu->setText(QCoreApplication::translate("MainWindow", "\346\243\213\350\255\234\350\262\274\343\202\212\344\273\230\343\201\221", nullptr));
        actionCopyBoardToClipboard->setText(QCoreApplication::translate("MainWindow", "\345\260\206\346\243\213\347\233\244\347\224\273\345\203\217\343\202\263\343\203\224\343\203\274", nullptr));
        actionCopyEvalGraphToClipboard->setText(QCoreApplication::translate("MainWindow", "\350\251\225\344\276\241\345\200\244\343\202\260\343\203\251\343\203\225\347\224\273\345\203\217\343\202\263\343\203\224\343\203\274", nullptr));
        actionFlipBoard->setText(QCoreApplication::translate("MainWindow", "\347\233\244\351\235\242\343\201\256\345\233\236\350\273\242", nullptr));
        actionStartGame->setText(QCoreApplication::translate("MainWindow", "\345\257\276\345\261\200", nullptr));
        actionResign->setText(QCoreApplication::translate("MainWindow", "\346\212\225\344\272\206", nullptr));
        actionBreakOffGame->setText(QCoreApplication::translate("MainWindow", "\344\270\255\346\226\255", nullptr));
#if QT_CONFIG(whatsthis)
        actionBreakOffGame->setWhatsThis(QString());
#endif // QT_CONFIG(whatsthis)
        actionQuit->setText(QCoreApplication::translate("MainWindow", "\347\265\202\344\272\206", nullptr));
        actionAnalyzeKifu->setText(QCoreApplication::translate("MainWindow", "\346\243\213\350\255\234\350\247\243\346\236\220", nullptr));
        actionStartEditPosition->setText(QCoreApplication::translate("MainWindow", "\345\261\200\351\235\242\347\267\250\351\233\206\351\226\213\345\247\213", nullptr));
        actionSetHiratePosition->setText(QCoreApplication::translate("MainWindow", "\345\271\263\346\211\213\345\210\235\346\234\237\351\205\215\347\275\256", nullptr));
        actionSetTsumePosition->setText(QCoreApplication::translate("MainWindow", "\350\251\260\345\260\206\346\243\213\345\210\235\346\234\237\351\205\215\347\275\256", nullptr));
        actionReturnAllPiecesToStand->setText(QCoreApplication::translate("MainWindow", "\345\205\250\343\201\246\343\201\256\351\247\222\343\202\222\351\247\222\345\217\260\343\201\270", nullptr));
        actionChangeTurn->setText(QCoreApplication::translate("MainWindow", "\346\211\213\347\225\252\345\244\211\346\233\264", nullptr));
        actionEngineSettings->setText(QCoreApplication::translate("MainWindow", "\343\202\250\343\203\263\343\202\270\343\203\263\350\250\255\345\256\232", nullptr));
        actionOpenWebsite->setText(QCoreApplication::translate("MainWindow", "\343\203\233\343\203\274\343\203\240\343\203\232\343\203\274\343\202\270", nullptr));
        actionUsage->setText(QCoreApplication::translate("MainWindow", "\344\275\277\343\201\204\346\226\271", nullptr));
        actionVersionInfo->setText(QCoreApplication::translate("MainWindow", "\343\203\220\343\203\274\343\202\270\343\203\247\343\203\263\346\203\205\345\240\261", nullptr));
        actionAboutQt->setText(QCoreApplication::translate("MainWindow", "Qt\343\201\253\343\201\244\343\201\204\343\201\246", nullptr));
        actionCopyKIF->setText(QCoreApplication::translate("MainWindow", "KIF\345\275\242\345\274\217", nullptr));
        actionCopyKI2->setText(QCoreApplication::translate("MainWindow", "KI2\345\275\242\345\274\217", nullptr));
        actionCopyCSA->setText(QCoreApplication::translate("MainWindow", "CSA\345\275\242\345\274\217", nullptr));
        actionCopyUSICurrent->setText(QCoreApplication::translate("MainWindow", "USI\345\275\242\345\274\217\357\274\210\347\217\276\345\234\250\343\201\256\346\214\207\343\201\227\346\211\213\343\201\276\343\201\247\357\274\211", nullptr));
        actionCopySFEN->setText(QCoreApplication::translate("MainWindow", "SFEN\345\275\242\345\274\217", nullptr));
        actionCopyBOD->setText(QCoreApplication::translate("MainWindow", "BOD\345\275\242\345\274\217", nullptr));
        actionNewGame->setText(QCoreApplication::translate("MainWindow", "\346\226\260\350\246\217", nullptr));
        actionOpenKifuFile->setText(QCoreApplication::translate("MainWindow", "\351\226\213\343\201\217", nullptr));
#if QT_CONFIG(shortcut)
        actionOpenKifuFile->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+O", nullptr));
#endif // QT_CONFIG(shortcut)
        actionUndoMove->setText(QCoreApplication::translate("MainWindow", "\345\276\205\343\201\243\343\201\237", nullptr));
        actionMakeImmediateMove->setText(QCoreApplication::translate("MainWindow", "\343\201\231\343\201\220\346\214\207\343\201\225\343\201\233\343\202\213", nullptr));
        actionEnlargeBoard->setText(QCoreApplication::translate("MainWindow", "\345\260\206\346\243\213\347\233\244\343\201\256\346\213\241\345\244\247", nullptr));
#if QT_CONFIG(shortcut)
        actionEnlargeBoard->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl++", nullptr));
#endif // QT_CONFIG(shortcut)
        actionShrinkBoard->setText(QCoreApplication::translate("MainWindow", "\345\260\206\346\243\213\347\233\244\343\201\256\347\270\256\345\260\217", nullptr));
#if QT_CONFIG(shortcut)
        actionShrinkBoard->setShortcut(QCoreApplication::translate("MainWindow", "Ctrl+-", nullptr));
#endif // QT_CONFIG(shortcut)
        actionEndEditPosition->setText(QCoreApplication::translate("MainWindow", "\345\261\200\351\235\242\347\267\250\351\233\206\347\265\202\344\272\206", nullptr));
        actionTsumeShogiSearch->setText(QCoreApplication::translate("MainWindow", "\350\251\260\343\201\277\346\216\242\347\264\242", nullptr));
        actionStopTsumeSearch->setText(QCoreApplication::translate("MainWindow", "\350\251\260\343\201\277\346\216\242\347\264\242\344\270\255\346\255\242", nullptr));
        actionJishogiScore->setText(QCoreApplication::translate("MainWindow", "\346\214\201\345\260\206\346\243\213\347\202\271\346\225\260", nullptr));
        actionNyugyokuDeclaration->setText(QCoreApplication::translate("MainWindow", "\345\205\245\347\216\211\345\256\243\350\250\200", nullptr));
        actionCopyUSIAll->setText(QCoreApplication::translate("MainWindow", "USI\345\275\242\345\274\217\357\274\210\345\205\250\343\201\246\357\274\211", nullptr));
        actionCopyJKF->setText(QCoreApplication::translate("MainWindow", "JSON\346\243\213\350\255\234\343\203\225\343\202\251\343\203\274\343\203\236\343\203\203\343\203\210", nullptr));
        actionCopyUSEN->setText(QCoreApplication::translate("MainWindow", "USEN", nullptr));
        actionCSA->setText(QCoreApplication::translate("MainWindow", "\351\200\232\344\277\241\345\257\276\345\261\200\357\274\210CSA\357\274\211", nullptr));
        actionCancelAnalyzeKifu->setText(QCoreApplication::translate("MainWindow", "\346\243\213\350\255\234\350\247\243\346\236\220\344\270\255\346\255\242", nullptr));
        actionMenuWindow->setText(QCoreApplication::translate("MainWindow", "\343\203\241\343\203\213\343\203\245\343\203\274", nullptr));
        actionLanguageSystem->setText(QCoreApplication::translate("MainWindow", "\343\202\267\343\202\271\343\203\206\343\203\240\350\250\255\345\256\232\343\201\253\345\276\223\343\201\206", nullptr));
        actionLanguageJapanese->setText(QCoreApplication::translate("MainWindow", "\346\227\245\346\234\254\350\252\236", nullptr));
        actionLanguageEnglish->setText(QCoreApplication::translate("MainWindow", "English", nullptr));
        actionToolBar->setText(QCoreApplication::translate("MainWindow", "\343\203\204\343\203\274\343\203\253\343\203\220\343\203\274", nullptr));
        actionSfenCollectionViewer->setText(QCoreApplication::translate("MainWindow", "\345\261\200\351\235\242\351\233\206\343\203\223\343\203\245\343\203\274\343\202\242", nullptr));
        actionResetDockLayout->setText(QCoreApplication::translate("MainWindow", "\343\203\211\343\203\203\343\202\257\343\203\254\343\202\244\343\202\242\343\202\246\343\203\210\343\202\222\343\203\252\343\202\273\343\203\203\343\203\210", nullptr));
        actionSaveDockLayout->setText(QCoreApplication::translate("MainWindow", "\343\203\211\343\203\203\343\202\257\343\203\254\343\202\244\343\202\242\343\202\246\343\203\210\343\202\222\344\277\235\345\255\230...", nullptr));
        actionLockDocks->setText(QCoreApplication::translate("MainWindow", "\343\203\211\343\203\203\343\202\257\343\202\222\345\233\272\345\256\232", nullptr));
        actionSavedLayoutsPlaceholder->setText(QCoreApplication::translate("MainWindow", "\357\274\210\344\277\235\345\255\230\346\270\210\343\201\277\343\203\254\343\202\244\343\202\242\343\202\246\343\203\210\343\201\252\343\201\227\357\274\211", nullptr));
        actionSaveEvaluationGraph->setText(QCoreApplication::translate("MainWindow", "\350\251\225\344\276\241\345\200\244\343\202\260\343\203\251\343\203\225\343\201\256\347\224\273\345\203\217\343\202\222\343\203\225\343\202\241\343\202\244\343\203\253\343\201\253\344\277\235\345\255\230", nullptr));
        actionTsumeshogiGenerator->setText(QCoreApplication::translate("MainWindow", "\350\251\260\345\260\206\346\243\213\345\261\200\351\235\242\347\224\237\346\210\220", nullptr));
        File->setTitle(QCoreApplication::translate("MainWindow", "\343\203\225\343\202\241\343\202\244\343\203\253(F)", nullptr));
        Edit->setTitle(QCoreApplication::translate("MainWindow", "\347\267\250\351\233\206(E)", nullptr));
        copyGameRecord->setTitle(QCoreApplication::translate("MainWindow", "\346\243\213\350\255\234\343\202\263\343\203\224\343\203\274", nullptr));
        shogiPositionCopy->setTitle(QCoreApplication::translate("MainWindow", "\345\261\200\351\235\242\343\202\263\343\203\224\343\203\274", nullptr));
        Display->setTitle(QCoreApplication::translate("MainWindow", "\350\241\250\347\244\272(I)", nullptr));
        menuSavedLayouts->setTitle(QCoreApplication::translate("MainWindow", "\344\277\235\345\255\230\346\270\210\343\201\277\343\203\254\343\202\244\343\202\242\343\202\246\343\203\210", nullptr));
        Game->setTitle(QCoreApplication::translate("MainWindow", "\345\257\276\345\261\200(G)", nullptr));
        Setting->setTitle(QCoreApplication::translate("MainWindow", "\350\250\255\345\256\232(S)", nullptr));
        menuLanguage->setTitle(QCoreApplication::translate("MainWindow", "\350\250\200\350\252\236\350\250\255\345\256\232", nullptr));
        Help->setTitle(QCoreApplication::translate("MainWindow", "\343\203\230\343\203\253\343\203\227(H)", nullptr));
        toolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
